const image = {
    a: require('./Chat/A.png'),
    b: require('./Chat/A.png'),
    Al: require('./Chat/Al.png'),
    H2O: require('./Chat/H2O.png'),
    O2: require('./Chat/O2.png'),
    CaO: require('./Chat/CaO.png'),
    SO2: require('./Chat/SO2.png'),
    Na2O: require('./Chat/Na2O.png'),
    Na: require('./Chat/Na.png'),
    K2O: require('./Chat/K2O.png'),
    N2O5: require('./Chat/N2O5.png'),
    SO3: require('./Chat/SO3.png'),
    Fe: require('./Chat/Fe.png'),
    P: require('./Chat/P.png'),
    S: require('./Chat/S.png'),
    Mg: require('./Chat/Mg.png'),
    C: require('./Chat/C.png'),
    CH4: require('./Chat/CH4.png'),
    Cu: require('./Chat/Cu.png'),
    AlOH3: require('./Chat/Al(OH)3.png'),
    Al2O3: require('./Chat/Al2O3.png'),
    Al2O3rs: require('./result/Al2O3.gif'),
    Zn: require('./Chat/Zn.png'),
    // K2MnO4: require('./Chat/K2MnO4.png'),
    HCl: require('./Chat/HCl.png'),
    CaCO3: require('./Chat/CaCO3.png'),
    HNO3: require('./Chat/HNO3.png'),
    CuSO4: require('./Chat/CuSO4.png'),
    CO2: require('./Chat/CO2.png'),
    CuCl2: require('./Chat/CuCl2.png'),
    H2SO4: require('./Chat/H2SO4.png'),
    NaOHrs: require('./result/NaOHrs.gif'),
    H2SO3: require('./Chat/H2SO3.png'),
    Fe3O4: require('./Chat/Fe3O4.png'),
    Fe3O4: require('./result/Fe3O4.gif'),
    //AlCl3: require('./Chat/AlCl3.png'),
    BaO:require('./Chat/BaO.png'),
    AgNO3: require('./Chat/AgNO3.png'),
    H2: require('./Chat/H2.png'),
    CaOH2: require('./Chat/Ca(OH)2.png'),
    P2O5: require('./Chat/P2O5.png'),
    ZnCl2: require('./Chat/ZnCl2.png'),
    MgO: require('./Chat/MgO.png'),
    MgOrs: require('./result/MgOrs.gif'),
    NaCl: require('./Chat/NaCl.png'),
    CaCl2: require('./Chat/CaCl2.png'),
    FeCl2rs: require('./result/FeCl2rs.gif'),
    CuOrs: require('./result/CuOrs.gif'),
    SO2rs: require('./result/SO2rs.gif'),
    ZnCl2rs: require('./result/ZnCl2rs.gif'),
    P2O5rs: require('./result/P2O5rs.gif'),
    AlCl3rs: require('./result/AlCl3rs.gif'),
    Na2Ors: require('./result/Na2Ors.gif'),
    COrs: require('./result/COrs.gif'),
    BaOH2rs: require('./result/Ba(OH)2rs.gif'),
    CaCl2rs: require('./result/CaCl2rs.gif'),
    CuCl2rs: require('./result/CuCl2rs.gif'),
    KClrs: require('./result/KClrs.gif'),
    LiOHrs: require('./result/LiOHrs.gif'),
    NaClrs: require('./result/NaClrs.gif'),
    //CuOH2: require('./Chat/CuOH2.png'),
    KOH: require('./Chat/KOH.png'),
    Li: require('./Chat/Li.png'),
    Na2CO3: require('./Chat/Na2CO3.png'),
    

    //Hình cho màn hình danh sách chức năng
    video: require('./video.png'),
    chemist: require('./chemistAvar.png'),
    bth: require('./bth.png'),
    back: require('./back.png'),
}

export default image